
'use client';

import React, { useState } from 'react';
import { AlibiSetupScreen } from './AlibiSetupScreen';
import { CaseFile } from './CaseFile';
import { type GenerateMysteryOutput } from '@/ai/schemas/alibi-archives';
import { useCreations } from '@/context/CreationsContext';

export function AlibiArchives() {
    const [mystery, setMystery] = useState<GenerateMysteryOutput | null>(null);
    const { creations } = useCreations();

    // This component now acts as a renderer for mysteries generated by the AI agent.
    // We look for the latest mystery in the creations context.
    React.useEffect(() => {
        const latestMystery = creations
            .filter(c => c.type === 'file' && c.data?.caseTitle)
            .sort((a, b) => b.timestamp - a.timestamp)[0];

        if (latestMystery && latestMystery.data) {
            setMystery(latestMystery.data as GenerateMysteryOutput);
        }
    }, [creations]);
    
    const handleReset = () => {
        setMystery(null);
    }

    if (mystery) {
        return <CaseFile mystery={mystery} onReset={handleReset} />;
    }

    return <AlibiSetupScreen onGenerate={() => {}} isLoading={false} />;
}
